# Generated by Django 4.1 on 2023-11-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photos',
            new_name='slider',
        ),
    ]
