# Generated by Django 4.1 on 2023-11-16 11:21

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('page', '0002_rename_photos_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='photo_slider', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
